version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
      time: '03:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
    ignore:
      - dependency-name: 'chai'
        versions: ['>=5.0.0']
      - dependency-name: 'eslint'
        versions: ['>=9.0.0']
    groups:
      typescript and eslint:
        patterns:
          - '*typescript*'
          - '*eslint*'
      types:
        patterns:
          - '@types/*'
