name: Build on PR

on:
  pull_request:
    branches:
      - master

jobs:
  run:
    name: Build on PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm install
      - run: npm run build --if-present
      - run: npm test
