name: Build/Release on Push

on:
  push:
    branches:
      - master

jobs:
  run:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

      - name: Semantic Releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release