name: Build/Release

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  run:
    name: Build/Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

      - name: Semantic Releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release