name: Build/Deploy on Push

on:
  push:
    branches:
      - master

jobs:
  run:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

      - name: Semantic Releasing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
        
      - name: Publishing Action
        uses: technote-space/release-github-actions@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: ng-update[bot]
          COMMIT_EMAIL: ng-update@users.noreply.github.com
          COMMIT_MESSAGE: "chore(release): publishing new version from '${{github.ref}}'"
          OUTPUT_BUILD_INFO_FILENAME: build.json
          BRANCH_NAME: releases
